// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Inter_Tight,Manrope  } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/ScrollHelper/ScrollEffect";

export const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter-tight",
});

export const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-manrope",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${interTight.variable}
          ${poppins.variable}
          ${manrope.variable}
          antialiased
        `}
      >
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
